import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.scss';

import Footer from '@components/footer';
import Script from 'next/script';
import GoogleAnalytics from './google-analytics';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <GoogleAnalytics />
      <body
        className={`${roboto.className} text-default relative flex items-center h-full w-full flex-col bg-black`}
      >
        <div className="max-w-[1080px] absolute">
          <main className="flex justify-center sm:px-8 min-h-screen ">
            <div className="relative w-full ">{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
